baseURL                = "https://issue.techpawz.com/"
languageCode           = "ko-KR"
defaultContentLanguage = "ko"
title                  = "테크포우즈 Issue"
theme                  = "blowfish"
themesDir              = "/Users/twinssn/Projects/shared-themes"
summaryLength          = 0

[pagination]
  pagerSize = 10

[outputs]
  home    = ["HTML", "RSS", "JSON", "Sitemap"]
  section = ["HTML"]
  page    = ["HTML"]

[permalinks]
  posts = "/:slug/"

[sitemap]
  changefreq    = "daily"
  priority      = 0.8
  filename      = "sitemap.xml"
  excludedKinds = ["taxonomy", "term", "section"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      strikethrough = false

[taxonomies]
  category = "categories"
  tag      = "tags"
  author   = "authors"

[params]
[params.homepage]
  layout = "background"
  showRecent = true

[params.article]
  showTableOfContents = false

[params.advertisement]
  adsense = "ca-pub-8772455780561463"
  topSlot = "6685009950"
  inArticleSlot = "6685009950"

[params.customCSS]
  css = ["css/custom.css"]
